sonar.projectKey=Markec-kramer_RIRS-solo
sonar.organization=markec-kramer
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/coverage/**,**/.github/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
